# docker-compose up
version: '3'
services:
  db:
    image: postgres:11-alpine
  redis:
    image: redis:5-alpine
  web:
    image: zungenkatze/werbeskip
    command: sh docker-entrypoint.sh
    ports:
      - 80:80
    depends_on:
      - redis
      - db
  update_handler:
    image: zungenkatze/werbeskip
    command: python update_handler.py
    depends_on:
      - redis
      - db
      - web
