# docker-compose up
version: '3'
services:
  db:
    image: postgres:11-alpine
  redis:
    image: redis:5-alpine
  web:
    image: werbeskip
    build: .
    command: sh docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
  updater:
    image: werbeskip
    build: .
    command: python update_handler.py
    depends_on:
      - redis
      - db
      - web
