version: '3'
services:
  db:
    image: postgres
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
  updater:
    build: .
    command: python update_handler.py
    depends_on:
      - redis
      - web

