# Generated by Django 2.0.7 on 2018-08-12 11:35

from django.db import migrations


def init_room(apps, schema_editor):
    Room = apps.get_model('app', 'Room')
    room, created = Room.objects.get_or_create(title="main", staff_only=False)
    room.save()


def init_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    user, created = User.objects.get_or_create(is_superuser=True, username="updater", is_staff=True, password="pbkdf2_sha256$100000$hnXs6xgXb8Mu$r6wIJBXB09i8exxM7Br1UEyGdObnLPU3mN4nfqY5y/s=")
    user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.RunPython(init_room),
        migrations.RunPython(init_user),
    ]
