# Generated by Django 2.0.7 on 2018-08-12 11:35

from django.db import migrations


def init_room(apps, schema_editor):
    Room = apps.get_model('app', 'Room')
    room, created = Room.objects.get_or_create(title="main", staff_only=False)
    room.save()


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
        ('auth', '__first__'),
    ]

    operations = [
        migrations.RunPython(init_room),
    ]
